name: CD WORKFLOW

on:
  push:
    branches:
      - development
      - main

  pull_request:
    branches:
    - main

    types:
    - closed
   
env:
  DOTNET_VERSION: '5.0.301' 
  AZURE_WEBAPP_NAME: DWebApp
  AZURE_WEBAPP_Path: "."

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Setup .NET Core - restore - test
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - run: dotnet restore
    - run: dotnet test --no-restore --verbosity normal --collect "Code Coverage"

    - name: Upload Test Coverage
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-result
        path: DavidAppTest/TestResults
      
    - name: Build Project + publish
      run: | 
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_Path }}/myapp'
        ls

    - name: Upload build folder
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: DavidAppTest/bin



    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: '${{ env.AZURE_WEBAPP_Path }}/myapp'


  release:
    needs: build
    name: release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event.pull_request.merged == true
    steps:
      - name: Build release
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
