name: CI WORKFLOW

on:
  pull_request:
    branches: 
      - development
      - main

    types:
      - opened
      - synchronize
   
env:
  DOTNET_VERSION: '5.0.301' 

jobs:
  build-test-coverage:
    name: Build Test Coverage
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core - restore - test
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - run: dotnet restore
    - run: dotnet test --no-restore --verbosity normal --collect "Code Coverage"

    - name: Upload Test Coverage
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-result
        path: DavidAppTest/TestResults
   