name: Deploy Via Issue

on:
  issues:
    types:
      - opened
      - pinned
      - edited
      - reopened
      - labeled

env:
  VERSION: "0.0.0.0"


# /[[:digit:]]\+\
jobs:
  printlabel:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: printlabel
      if: "!contains(github.event.issue.labels.*.name, 'deploy_env')"
      run: |
        echo "Label names"
        echo "${{ github.event.label.name }}"
        regex='[0-9]\.[0-9]\.[0-9]\.[0-9]'
        if [[ "${{ github.event.label.name }}" =~ $regex ]]; then
        echo "Label matched"
        echo "VERSION=${{ github.event.label.name }}" >> $GITHUB_ENV
        exit 0
        else
        echo "Not matched"
        exit 1
        fi

    - name: Print variable
      run: echo ${{ env.VERSION }}
    
