name: Deploy Via Issue

on:
  issues:
    types:
      - opened
      - pinned
      - edited
      - labeled
      - reopened

env:
  VERSION: "0.0.0.0"


# /[[:digit:]]\+\
jobs:
  printlabel:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: printlabel
      if: "contains(github.event.issue.labels.*.name, 'deploy_env') && github.event.label.name != 'deploy_env'"
      run: |
        regex='[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+'
        if [[ "${{ github.event.label.name }}" =~ $regex ]]; then
        echo "Label matched"
        echo "${{ github.event.label.name }}"
        echo "SCM_VERSION=${{ github.event.label.name }}" >> $GITHUB_ENV
        exit 0
        else
        echo "Label Not matched"
        exit 1
        fi

    - name: Print variable
      run: echo ${{ env.SCM_VERSION }}
    
