
name: David App Test

on: [push]

jobs:
  runs-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Starting David app workflow"

      - name: Current path
        run: |
          echo "current path"
          pwd


      - name: dotner versions
        run: | 
          dotnet -v
          dotnet --version
          


