
name: David App Test

on: [push]

jobs:
  runs-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Starting David app workflow"

      - name: run dotnet test
        run: |
          which dotnet
          dotnet test

      - name: multiline script
        run: | 
          node -v
          npm -v