
name: Check for Duplciates in Sql Scripts

on:
  pull_request:
    branches:
      - main

    types:
      - opened
      - synchronize


jobs:
  check-for-duplicates:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Check For Duplicates
         run: |
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "Github workspace ${{ env.GITHUB_WORKSPACE }}"
          pwd
          ls
          find EBS.Core.Web.MVC/InstallFiles/ -name *.sql ! -path '*-.old*' | awk -F "/" '{split($NF,a,"."); print sprintf("%s/%s/%s/%s",$1,$2,$3,a[1])}' | uniq -D


# jobs:
#   runs-shell-command:
#     runs-on: ubuntu-latest
#     steps:
#       - name: echo a string
#         run: echo "Starting David app workflow"

#       - name: Current path
#         run: |
#           echo "current path"
#           pwd
#           echo "List directios"
#           ls
#       - name: Python commands
#         run : |
#           import platform
#           import requests
#           print(platform.processor())
#         shell: python

#   runs-windows-command:
#     runs-on: windows-latest
#     steps:
#       - name: Windows commands
#         run: |
#           Get-Location
#           dir
#       - name: Bash Comands
#         run: |
#           pwd
#           echo "from bash"
#         shell: bash
